### ISSUE TITLE
Can't seem to pass variables

### ISSUE THREAD

**Issue by asteurba** [LastAbyss/SimpleGraphQL-For-Unity#1]
Hi,
I've been trying out the library and I've had mixed successes.
Queries without any variables work, including the ones that require JWT authorisation, which is awesome!

I can't get mutations to work however. Keep getting backend errors that the variables are not provided.
Graphql document: 
```
mutation loginWithPassword($email:String! $password: String!) 
{
  loginWithPassword(email: $email, password: $password) {
    tokens {
      accessToken
    },
    user {
      profile {
        fullName
      }
    }
  }
}
```

Code to send the mutation: 
```
public async void PostLogin(string email, string password)
  {
    var graphQL = new GraphQLClient(Config);

    Query loginMutation = graphQL.FindQuery("Login");
    string results = await graphQL.SendAsync(
        loginMutation,
        "jwt",
        null,
        new Dictionary<string, string>
        {
                {"$email", email},
                {"$password", password}
        }
    );
    Debug.Log(results);
  }
```

Stacktrace: 
`{"errors":[{"message":"Variable \"$email\" of required type \"String!\" was not provided.","locations":[{"line":1,"column":28}],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["GraphQLError: Variable \"$email\" of required type \"String!\" was not provided.","    at _loop (/app/node_modules/graphql/execution/values.js:94:17)","    at coerceVariableValues (/app/node_modules/graphql/execution/values.js:121:16)","    at getVariableValues (/app/node_modules/graphql/execution/values.js:50:19)","    at buildExecutionContext (/app/node_modules/graphql/execution/execute.js:206:61)","    at executeImpl (/app/node_modules/graphql/execution/execute.js:104:20)","    at Object.execute (/app/node_modules/graphql/execution/execute.js:63:35)","    at /app/node_modules/apollo-server-core/src/requestPipeline.ts:545:22","    at Generator.next (<anonymous>)","    at /app/node_modules/apollo-server-core/dist/requestPipeline.js:8:71","    at new Promise (<anonymous>)"]}}},{"message":"Variable \"$password\" of required type \"String!\" was not provided.","locations":[{"line":1,"column":43}],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["GraphQLError: Variable \"$password\" of required type \"String!\" was not provided.","    at _loop (/app/node_modules/graphql/execution/values.js:94:17)","    at coerceVariableValues (/app/node_modules/graphql/execution/values.js:121:16)","    at getVariableValues (/app/node_modules/graphql/execution/values.js:50:19)","    at buildExecutionContext (/app/node_modules/graphql/execution/execute.js:206:61)","    at executeImpl (/app/node_modules/graphql/execution/execute.js:104:20)","    at Object.execute (/app/node_modules/graphql/execution/execute.js:63:35)","    at /app/node_modules/apollo-server-core/src/requestPipeline.ts:545:22","    at Generator.next (<anonymous>)","    at /app/node_modules/apollo-server-core/dist/requestPipeline.js:8:71","    at new Promise (<anonymous>)"]}}}]}`

I've verified the mutation in graphql playground and it's definitely correctly formed. Also tried putting in hardcoded variables and writing the variable keys without $.

Am I missing something? I'm pretty new to C#, so might just be that I'm making a mistake somewhere....

**Comment by NavidK0** [comment]
Hi!

There is a simple mistake in the previous version where I used a full string Dictionary for variables instead of <string, object>, which causes all non string variables to not work. Commit 9b44fdcb1d691192656ef5380a0c42b00b8d0fae should fix that issue.

Now, you're passing in strings so that shouldn't trigger that problem. I see you're passing in "$email" which should be "email." Your query also doesn't have a comma next to the parameters, though I'm not sure if that's a required component of GraphQL.

```
($email: String!, $password: String!)
```

**Comment by asteurba** [comment]
Thanks for the quick reply!
The "email" instead of "$email" didn't help actually, forgot to mention that I tried that as well.
In the end I got it going by using named parameters in the method call:
```
 string results = await graphQL.SendAsync(
        query: loginMutation,
        authScheme: "jwt",
        authToken: null,
        variables: new Dictionary<string, string>
        {
                {"email", email},
                {"password", password}
        }
    );
```
Again, I'm pretty new to C#, so not sure whether this is a recommended way to working, but this seems to fix it. Any idea on why the non-named variation doesn't seem to work?

Also, the new commit will certainly come in handy, thanks for the work!

**Comment by NavidK0** [comment]
I think I figured out your issue, and it has to do with overloaded methods.
There are two forms of GraphQLClient.SendAsync():

```cs
public async Task<string> SendAsync(
            Query query,
            string authToken = null,
            Dictionary<string, object> variables = null,
            Dictionary<string, string> headers = null
        )
```
and
```cs
public async Task<string> SendAsync(
            Query query,
            string authScheme = "Bearer",
            string authToken = null,
            Dictionary<string, object> variables = null,
            Dictionary<string, string> headers = null
        )
```

You were originally inadvertently calling the first overloaded method because you had it like this:
```cs
string results = await graphQL.SendAsync(
        loginMutation,
        "jwt",
        null,
        new Dictionary<string, string>
        {
                {"$email", email},
                {"$password", password}
        }
    );
```

Notice how four parameters are passed in? This actually calls the first method because `null` is passed into the `variables` Dictionary. This means you were actually passing in your variables as headers rather than variables, which is why you were getting that error. I didn't realize it until you mentioned that you had to use named parameters!

The way you do it is perfectly fine. An alternative would be this:
```cs
string results = await graphQL.SendAsync(
        loginMutation,
        "jwt",
        null,
        new Dictionary<string, string>
        {
                {"$email", email},
                {"$password", password}
        },
        null
    );
```
This would also guarantee that the five-parameter overloaded method is called every time.

PS:
No problem, by the way, I'm glad people are getting use out of my code, even if we're not actively using GraphQL in our projects.

**Comment by NavidK0** [comment]
Personally, I think I'm probably going to modify that API just a bit so other people don't run into the same problem in the future. It seems really easy to fall into that trap.

Edit:
Done 648470dbf06850d1c01a6b09484d4c0aca307b8b

NOTE: The example code above is now outdated due to the refactor changes. Please see the example code on the README for the new way to do it :)

**Comment by steuraa** [comment]
Hi Navid, thanks for the detailed reply, I had a look at the 2 implementations, but didn't think about the fact that my null for the token would trigger the first implementation with 4 parameters, dumb oversight on my part!

The 1.1.0 changes will indeed help with that issue I think! Thanks again for the work and should I encounter other issues, I'll let you know :)
