### ISSUE TITLE
IL2CPP Build Issue

### ISSUE THREAD

**Issue by RPloutarchou** [LastAbyss/SimpleGraphQL-For-Unity#3]
Hi, I have an app that uses this simple graphql package. The package seems to be working perfectly on Mono on both unity editor and android device but when i switch to scripting backend il2cpp I can only see the data on the editor but not on the android device.

**Comment by NavidK0** [comment]
Hello!

I have a feeling as to what could be causing this, though I don't remember any issues with IL2CPP when I actively used SimpleGraphQL.

I have updated the project to use Unity's Newtonsoft-JSON version instead of the internal version. As they say they already support IL2CPP, this may resolve your issue. Give 1.1.3 a try and let me know how it goes.

**Comment by sidhants** [comment]
> Hi, I have an app that uses this simple graphql package. The package seems to be working perfectly on Mono on both unity editor and android device but when i switch to scripting backend il2cpp I can only see the data on the editor but not on the android device.

Hi. Were you able to get the build issue resolved and test it out on android devices? 

I am also planning to try this library on IL2CPP platforms for mobile AR, Magic Leap headsets and hoping it will not have any issues and make graphQL integration simple and easy!
@NavidK0 Thanks to the devs for this effort because I remember struggling with IL2CPP issues and graphQL in the past. Most of the other libraries are using C# dynamics in the parsers (newtonsoft, simplejson) which is the problem on IL2CPP AOT platforms.

**Comment by RPloutarchou** [comment]
Hi. Thanks for the quick reply. I have updated the package to the latest and re-builder my app but I had no luck. The problem though does not seems to be with this package since I have created a fresh project and implemented some of my app's functions to test it and its working great. Some other package seems to be the problem. Thanks for looking into it so quickly.
