### ISSUE TITLE
Old projects not compiling after upgrading minor version

### ISSUE THREAD

**Issue by johanhelsing** [LastAbyss/SimpleGraphQL-For-Unity#41]
After upgrading, my project stopped working due to this change:

https://github.com/LastAbyss/SimpleGraphQL-For-Unity/commit/b4a473becf9d0558d1b103dddc1826c23a81f582

The code that stopped building

```c#
            var result = await apiClient.Send(
                () => new { result = resultTypeResolver() },
                request,
                null,
                token,
                scheme);
```

```c#
            var result = await apiClient.Send(
                () => new { result = resultTypeResolver() },
                request,
                null, // <-- needed to add this argument after upgrading to latest version
                null,
                token,
                scheme);
```

We should probably either bump major version or restore an overload with the old api, or move the settings arg so it's the last overload.

**Comment by NavidK0** [comment]
Done with https://github.com/LastAbyss/SimpleGraphQL-For-Unity/commit/1e987605ca452ec62dd142b36a26b8f208257819

I think we are starting to reach the point where we may want to use a configuration object parameter (similar to JavaScript), instead of many parameters.

Perhaps something like `SendRequestSettings` or similar.

**Comment by NavidK0** [comment]
I think that API could look like

```cs
var result = await apiClient.Send(
	  () => new { result = resultTypeResolver() },
	  request,
	  new {
	      Token = token,
	      Scheme = scheme
	  }
  );
```
